### ISSUE TITLE
Migrate IdentityModel.AspNetCore.OAuth2Introspection here

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/foss#19]

**Comment by leastprivilege** [comment]
This would actually be a better fit for our AspNetCore extensions project?!

**Comment by josephdecock** [comment]
Closing as we'll do future introspection work in the aspnetcore extensions project.

**Comment by josephdecock** [comment]
See also: https://github.com/DuendeSoftware/aspnetcore/issues/12
