### ISSUE TITLE
Mark DateTimeExtensions obsolete

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/foss#40]
These are convenience functions to convert to and from unix epoch time. We could deprecate in favor of DateTimeOffset.FromUnixTimeSeconds and DateTimeOffset.ToUnixTimeSeconds (but verify that all supported platforms include those methods).

(Migrated from [IdentityModel](https://github.com/IdentityModel/IdentityModel/issues/573))

**Comment by josephdecock** [comment]
Flagged as a breaking change, even though we would `[Obsolete]` and not delete these methods.

**Comment by damianh** [comment]
Agreed with marking as `[Obsolete]` now and remove in a future major version.  Adjusting this issue to be `impact/non-breaking` and adding a new issue to remove them in future.
