### ISSUE TITLE
AccessTokenManagement .NET 9 Support

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/foss#45]

**Comment by devbeard** [comment]
@AndersAbel Any tentative timeline for the .NET 9 version? We managed to hit the issue with RevocationEndpoint metadata for our BFF clients.

**Comment by damianh** [comment]
@devbeard We've released a preview version to nuget.org https://www.nuget.org/packages/Duende.AccessTokenManagement/3.1.0-preview.1 that targets and supports .NET 9. Please try it out and report back :).

An update to BFF is on way also.

**Comment by devbeard** [comment]
Great news, glad to hear it @damianh

**Comment by damianh** [comment]
Going to close this as completed.
