### ISSUE TITLE
New OidcClient packages versions are not available via NuGet

### ISSUE THREAD

**Issue by GuillaumeErgole** [DuendeSoftware/foss#75]
Hello,

[https://www.nuget.org/packages/Duende.IdentityModel](https://www.nuget.org/packages/Duende.IdentityModel) talks about new versions for OidcClient packages but they are not available on NuGet repository.

[https://www.nuget.org/packages/Duende.IdentityModel.OidcClient](https://www.nuget.org/packages/Duende.IdentityModel.OidcClient)
[https://www.nuget.org/packages/Duende.IdentityModel.OidcClient.DPoP](https://www.nuget.org/packages/Duende.IdentityModel.OidcClient.DPoP)

And old packages have reference to [System.Text.Json 8.0.0](https://www.nuget.org/packages/System.Text.Json/8.0.0) with a vulnerability warning. I know, this can be fix by a direct reference to the 8.0.5 but I would prefer to also have the latest versions of the packages.

**Comment by josephdecock** [comment]
Sorry for the confusion - we're in the process of migrating OidcClient into this repo, and the Duende.OidcClient builds haven't been created yet. The readme reflects the goal/end-state, but while we get there it is clearly confusing.
